[currencies.credits]
description = ["<gray>Pièce d'une valeur de <gold><value><gray>."]
name_singular = "Crédit"
name_plural = "Crédits"
format = "###,##0.00"
physical_currencies = [
    { value = 0.01, material = "GLOWSTONE_DUST" },
    { value = 0.1, material = "GUNPOWDER" },
    { value = 1.0, material = "IRON_NUGGET" },
    { value = 64.0, material = "GOLD_NUGGET" },
    { value = 4096.0, material = "GOLD_INGOT" },
    { value = 262144.0, material = "GOLD_BLOCK" },
    { value = 16777216.0, material = "NETHERITE_INGOT" },
    { value = 1073741824.0, material = "NETHERITE_BLOCK" }
]

[currencies.shards]
description = ["<gray>Fragment ancestral issu de la", "<gray>création du monde de Pickaria."]
name_singular = "Éclat de Pickarite"
name_plural = "Éclats de Pickarite"
format = "###,##0.#"
physical_currencies = [
    {value = 1.0, material = "ECHO_SHARD"}
]

[currencies.keys]
description = ["<gray>Objet permettant l'achat de récompenses."]
name_singular = "Clé"
name_plural = "Clés"
format = "###,##0.#"
physical_currencies = [
    {value = 1.0, material = "TRIPWIRE_HOOK"}
]
