api-version: "1.20"
author: Quozul
description: Economy plugin
main: fr.pickaria.emerald.Main
name: Emerald
version: "1.0"
website: https://www.pickaria.fr

loader: fr.pickaria.Loader

dependencies:
  bootstrap:
    Vault:
      required: true
      join-classpath: true
      load: BEFORE

  server:
    Vault:
      required: true
      join-classpath: true
      load: BEFORE
